@startuml
entity Initiator
entity Responder


== Upgrade with security protocol from listener's multiaddr ==

... Security handshake ...

== Initial multistream handshake ==

Responder -> Initiator: /multistream/1.0.0
Initiator -> Responder: /multistream/1.0.0

== Negotiate stream multiplexer ==

Initiator -> Responder: /mplex/1.0.0
note left: Initiator proposes mplex for stream multiplexing

Responder -> Initiator: /mplex/1.0.0
note right: Responder supports mplex, echoes back protocol id
@enduml