@startuml

entity Initiator
entity Receiver
Initiator -> Receiver: Open connection

== Establish that both sides support multistream-select ==

note over Initiator, Receiver: Utilizing the bootstrap protocol negociation

Initiator -> Receiver: Send multistream protocol id
Receiver -> Initiator: Send multistream protocol id


== Negotiate protocol to use ==


loop until success, or Initiator gives up and closes channel
  Initiator -> Receiver: Send protocol id for desired protocol
  alt protocol is supported by Receiver
    Receiver -> Initiator: Echo back protocol id to indicate agreement
  else protocol is not supported
    Receiver -> Initiator: Send "na" (not available)
  end
end

== Use negotiated protocol ==

Initiator -> Receiver: Send protocol-specific message
Receiver -> Initiator: Send protocol-specific reply

@enduml
